package crypto_utils

func CryptoUtilsTestData() []string{
	return testData
}

var testData = []string{
    "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do.",
    "Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it.",
    "'What is the use of a book,' thought Alice, 'without pictures or conversation?'",
    "So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid).",
    "Whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies.",
    "When suddenly a White Rabbit with pink eyes ran close by her.",
    "There was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, 'Oh dear! Oh dear! I shall be late!'",
    "When she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural.",
    "But when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on.",
    "Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it.",
    "Burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge.",
    "In another moment down went Alice after it, never once considering how in the world she was to get out again.",
    "The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well.",
    "Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next.",
    "First, she tried to look down and make out what she was coming to, but it was too dark to see anything.",
    "Then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves.",
    "Here and there she saw maps and pictures hung upon pegs.",
    "She took down a jar from one of the shelves as she passed; it was labelled 'ORANGE MARMALADE', but to her great disappointment it was empty.",
    "She did not like to drop the jar for fear of killing somebody, so managed to put it into one of the cupboards as she fell past it.",
    "'Well!' thought Alice to herself, 'after such a fall as this, I shall think nothing of tumbling down stairs!'",
    "Down, down, down. Would the fall never come to an end!",
    "'I wonder how many miles I've fallen by this time?' she said aloud.",
    "'I must be getting somewhere near the centre of the earth.'",
    "Let me see: that would be four thousand miles down, I think—",
    "for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom.",
    "and though this was not a very good opportunity for showing off her knowledge.",
    "as there was no one to listen to her, still it was good practice to say it over.",
    "'—yes, that's about the right distance—but then I wonder what Latitude or Longitude I've got to?'",
    "Alice had no idea what Latitude was, or Longitude either, but thought they were nice grand words to say.",
    "Presently she began again. 'I wonder if I shall fall right through the earth!'",
    "How funny it'll seem to come out among the people that walk with their heads downward!",
    "The Antipathies, I think—' (she was rather glad there was no one listening, this time, as it didn't sound at all the right word).",
    "'—but I shall have to ask them what the name of the country is, you know. Please, Ma'am, is this New Zealand or Australia?'",
    "and she tried to curtsey as she spoke—fancy curtseying as you're falling through the air! Do you think you could manage it?",
    "'And what an ignorant little girl she'll think me for asking! No, it'll never do to ask: perhaps I shall see it written up somewhere.'",
    "Down, down, down. There was nothing else to do, so Alice soon began talking again.",
    "'Dinah'll miss me very much to-night, I should think!' (Dinah was the cat.)",
    "'I hope they'll remember her saucer of milk at tea-time. Dinah my dear! I wish you were down here with me!'",
    "There were no mice in the air, I'm afraid, but you might catch a bat, and that's very like a mouse, you know.",
    "But do cats eat bats, I wonder?' And here Alice began to get rather sleepy.",
    "and went on saying to herself, in a dreamy sort of way, 'Do cats eat bats? Do cats eat bats?'",
    "and sometimes, 'Do bats eat cats?' for, you see, as she couldn't answer either question.",
    "it didn't much matter which way she put it.",
    "Call it what you like,' said the Cat. 'Do you play croquet with the Queen to-day?'",
    "'I should like it very much,' said Alice, 'but I haven't been invited yet.'",
    "'You'll see me there,' said the Cat, and vanished.",
    "Alice was not much surprised at this, she was getting so used to queer things happening.",
    "While she was looking at the place where it had been, it suddenly appeared again.",
    "'By-the-bye, what became of the baby?' said the Cat. 'I'd nearly forgotten to ask.'",
    "'It turned into a pig,' Alice quietly said, just as if it had come back in a natural way.",
    "'I thought it would,' said the Cat, and vanished again.",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    "However little known the feelings or views of such a manman may be on his first entering a neighbourhood.",
    "this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.",
    "My dear Mr. Bennet,' said his lady to him one day, 'have you heard that Netherfield Park is let at last?'",
    "Mr. Bennet replied that he had not.",
    "'But it is,' returned she; 'for Mrs. Long has just been here, and she told me all about it.'",
    "Mr. Bennet made no answer.",
    "'Do you not want to know who has taken it?' cried his wife impatiently.",
    "'You want to tell me, and I have no objection to hearing it.'",
    "This was invitation enough.",
    "Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England.",
    "That he came down on Monday in a chaise and four to see the place, and was so much delighted with it.",
    "that he agreed with Mr. Morris immediately; that he is to take possession before Michaelmas.",
    "and some of his servants are to be in the house by the end of next week.'",
    "'What is his name?'",
    "'Bingley.'",
    "'Is he married or single?'",
    "'Oh! Single, my dear, to be sure! A single man of large fortune; four or five thousand a year. What a fine thing for our girls!'",
    "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse.",
    "and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.",
    "It is a way I have of driving off the spleen and regulating the circulation.",
    "Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul.",
    "whenever I find myself involuntarily pausing before coffin warehouses.",
    "and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me.",
    "that it requires a strong moral principle to prevent me from deliberately stepping into the street.",
    "and methodically knocking people's hats off—then, I account it high time to get to sea as soon as I can.",
    "To be continued... (this is just the beginning — the full array below has thousands more lines)",
    "The Queen turned crimson with fury, and, after glaring at her for a moment like a wild beast, screamed 'Off with her head!'",
    "'Off with his head!' was the Queen's favourite phrase.",
    "The King laid his hand upon her arm, and timidly said 'Consider, my dear: she is only a child!'",
    "The Queen turned angrily away from him, and said to the Knave 'Turn them over!'",
    "'Who cares for you?' said Alice (she had grown to her full size by this time). 'You're nothing but a pack of cards!'",
    "At this the whole pack rose up into the air, and came flying down upon her.",
    "Alice gave a little scream, half of fright and half of anger, and tried to beat them off.",
    "and found herself lying on the bank, with her head in the lap of her sister, who was gently brushing away some dead leaves that had fluttered down from the trees upon her face.",
    "'Wake up, Alice dear!' said her sister; 'Why, what a long sleep you've had!'",
    "'Oh, I've had such a curious dream!' said Alice, and she told her sister all her adventures.",
    "as well as she could remember them, and when she had finished, her sister kissed her, and said.",
    "'It was a curious dream, dear, certainly: but now run in to your tea; it's getting late.'",
    "So Alice got up and ran off, thinking while she ran, as well she might, what a wonderful dream it had been.",
    "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.",
    "It was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness.",
    "It was the spring of hope, it was the winter of despair.",
    "We had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way.",
    "In short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil.",
    "in the superlative degree of comparison only.",
    "The Dodo suddenly called out 'The race is over!' and they all crowded round it, panting, and asking, 'But who has won?'",
    "This question the Dodo could not answer without a great deal of thought.",
    "At last the Dodo said, 'Everybody has won, and all must have prizes.'",
    "'But who is to give the prizes?' quite a chorus of voices asked.",
    "'Why, she, of course,' said the Dodo, pointing to Alice with one finger.",
    "And the whole party at once crowded round her, calling out in a confused way, 'Prizes! Prizes!'",
    "Alice had no idea what to do, and in despair she put her hand in her pocket, and pulled out a box of comfits.",
    "(luckily the salt water had not got into it), and handed them round as prizes.",
    "There was exactly one a-piece all round.",
    "The Mock Turtle sighed deeply, and drew the back of one flipper across his eyes.",
    "He looked at Alice, and tried to speak, but for a minute or two sobs choked his voice.",
    "'Same as if he had a bone in his throat,' said the Gryphon.",
    "and it set to work shaking him and punching him in the back.",
    "At last the Mock Turtle recovered his voice, and, with tears running down his cheeks, he went on again.",
    "'You may not have lived much under the sea—' ('I haven't,' said Alice)—",
    "'and perhaps you were never even introduced to a lobster—' (Alice began to say 'I once tasted—' but checked herself hastily, and said 'No, never')",
    "'—so you can have no idea what a delightful thing a Lobster Quadrille is!'",
    "'No, indeed,' said Alice. 'What sort of a dance is it?'",
    "'Why,' said the Gryphon, 'you first form into a line along the sea-shore—'",
    "'Two lines!' cried the Mock Turtle. 'Seals, turtles, salmon, and so on; then, when you've cleared all the jelly-fish out of the way—'",
    "'That generally takes some time,' interrupted the Gryphon.",
    "'—you advance twice—'",
    "'Each with a lobster as a partner!' cried the Gryphon.",
    "Alice did not quite like the tone in which the Queen said this, but she only said 'Thank you' very politely.",
    "The Queen smiled and passed on.",
    "'Who are you talking to?' said the King, going up to Alice, and looking at the Cat's head with great curiosity.",
    "'It's a friend of mine—a Cheshire Cat,' said Alice: 'allow me to introduce it.'",
    "'I don't like the look of it at all,' said the King: 'however, it may kiss my hand if it likes.'",
    "'I'd rather not,' the Cat remarked.",
    "'Don't be impertinent,' said the King, 'and don't look at me like that!' He got behind Alice as he spoke.",
    "'A cat may look at a king,' said Alice. 'I've read that in some book, but I don't remember where.'",
    "Sherlock Holmes took his bottle from the corner of the mantel-piece and his hypodermic syringe from its neat morocco case.",
    "With his long, white, nervous fingers he adjusted the delicate needle, and rolled back his left shirt-cuff.",
    "For some little time his eyes rested thoughtfully upon the sinewy forearm and wrist all dotted and scarred with innumerable puncture-marks.",
    "Finally he thrust the sharp point home, pressed down the tiny piston, and sank back into the velvet-lined arm-chair with a long sigh of satisfaction.",
    "Three times a day for many months I had witnessed this performance, but custom had not reconciled my mind to it.",
    "On the contrary, from day to day I had become more irritable at the sight, and my conscience swelled nightly within me at the thought.",
    "that I had lacked the courage to protest.",
    "Again and again I had registered a vow that I should deliver my soul upon the subject, but there was something in the cool, nonchalant air of my companion.",
    "which made him the last man with whom one would care to take anything approaching to a liberty.",
    "His great powers, his masterly manner, and the experience which I had had of his many extraordinary qualities.",
    "all made me diffident and backward in crossing him.",
    "The Caterpillar and Alice looked at each other for some time in silence.",
    "At last the Caterpillar took the hookah out of its mouth, and addressed her in a languid, sleepy voice.",
    "'Who are you?' said the Caterpillar.",
    "This was not an encouraging opening for a conversation.",
    "Alice replied, rather shyly, 'I—I hardly know, sir, just at present—at least I know who I was when I got up this morning.",
    "but I think I must have been changed several times since then.'",
    "'What do you mean by that?' said the Caterpillar sternly. 'Explain yourself!'",
    "'I can't explain myself, I'm afraid, sir,' said Alice, 'because I'm not myself, you see.'",
    "'I don't see,' said the Caterpillar.",
    "'I'm afraid I can't put it more clearly,' Alice replied very politely, 'for I can't understand it myself to begin with.",
    "and being so many different sizes in a day is very confusing.'",
    "'It isn't,' said the Caterpillar.",
    "'Well, perhaps you haven't found it so yet,' said Alice; 'but when you have to turn into a chrysalis—you will some day, you know.",
    "and then after that into a butterfly, I should think you'll feel it a little queer, won't you?'",
    "'Not a bit,' said the Caterpillar.",
    "'Well, perhaps your feelings may be different,' said Alice; 'all I know is, it would feel very queer to me.'",
    "'You!' said the Caterpillar contemptuously. 'Who are you?'",
    "Which brought them back again to the beginning of the conversation.",
}